class ZCX_PLANNED_CHANGE_ERROR definition
  public
  inheriting from CX_STATIC_CHECK
  final
  create public .

public section.

  constants ZCX_PLANNED_CHANGE_ERROR type SOTR_CONC value 'FE2AF555CC021EE780EA22E34BD89AC5' ##NO_TEXT.
  constants NOT_FOUND type SOTR_CONC value 'FE2AF555CC021EE780EA22E34BD8BAC5' ##NO_TEXT.
  constants INSERT_FAILED type SOTR_CONC value 'FE2AF555CC021EE780EA22E34BD8DAC5' ##NO_TEXT.
  constants SAVE_FAILED type SOTR_CONC value 'FE2AF555CC021EE780EA22E34BD8FAC5' ##NO_TEXT.
  constants ERROR_MESSAGE type SOTR_CONC value 'FE2AF555CC021EE780EA22E34BD91AC5' ##NO_TEXT.
  constants INVALID_PARAMETER type SOTR_CONC value 'FE2AF555CC021EE780EA22E34BD93AC5' ##NO_TEXT.
  constants ORIGINAL_LINE_NOT_FOUND type SOTR_CONC value 'FE2AF555CC021EE780EA22E34BD95AC5' ##NO_TEXT.
  data OBJECTCLAS type CDOBJECTCL .
  data OBJECTID type CDOBJECTV .
  data CHANGENR type CDCHANGENR .
  data TABNAME type TABNAME .
  data MSG type STRING .
  data PARAM_NAME type STRING .

  methods CONSTRUCTOR
    importing
      !TEXTID like TEXTID optional
      !PREVIOUS like PREVIOUS optional
      !OBJECTCLAS type CDOBJECTCL optional
      !OBJECTID type CDOBJECTV optional
      !CHANGENR type CDCHANGENR optional
      !TABNAME type TABNAME optional
      !MSG type STRING optional
      !PARAM_NAME type STRING optional .
protected section.
private section.
ENDCLASS.



CLASS ZCX_PLANNED_CHANGE_ERROR IMPLEMENTATION.


  method CONSTRUCTOR.
CALL METHOD SUPER->CONSTRUCTOR
EXPORTING
TEXTID = TEXTID
PREVIOUS = PREVIOUS
.
 IF textid IS INITIAL.
   me->textid = ZCX_PLANNED_CHANGE_ERROR .
 ENDIF.
me->OBJECTCLAS = OBJECTCLAS .
me->OBJECTID = OBJECTID .
me->CHANGENR = CHANGENR .
me->TABNAME = TABNAME .
me->MSG = MSG .
me->PARAM_NAME = PARAM_NAME .
  endmethod.
ENDCLASS.
